version: "3.9"

services:
  fai-exercises:
    build: ../exercises/search/notebooks
    container_name: fai_search_exercises
    ports:
      - "8888:8888"
    volumes:
      # Mounts your local notebooks/ folder so edits are saved on your machine
      - ./notebooks:/home/jovyan/work/notebooks
    restart: unless-stopped
